/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anarchy_blurdemo_blur_FastBlur */

#ifndef _Included_com_anarchy_blurdemo_blur_FastBlur
#define _Included_com_anarchy_blurdemo_blur_FastBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anarchy_blurdemo_blur_FastBlur
 * Method:    fastBlurJni
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_anarchy_blurdemo_blur_FastBlur_fastBlurJni
  (JNIEnv *, jclass, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
